/**
 * server/solutions-seed.ts
 *
 * Jeu de départ pour la base de solutions naturelles (catalogue de référence
 * global, userId NULL). Inséré une seule fois au démarrage si aucune solution
 * globale n'existe encore. Le praticien peut ensuite ajouter ses propres entrées.
 *
 * ⚠️ Contenu d'information naturopathique (hygiène de vie), PAS un avis médical.
 * Chaque fiche inclut des précautions ; un disclaimer global est affiché dans l'UI.
 */

import { storage } from "./storage";

export interface SeedSolution {
  name: string;
  category: string; // Plante | Huile essentielle | Complément | Fleur de Bach
  properties: string;
  contraindications: string;
  usageNotes: string;
}

export const DEFAULT_SOLUTIONS: SeedSolution[] = [
  // ── Plantes ──
  { name: "Camomille romaine", category: "Plante", properties: "Apaise les tensions nerveuses et facilite la digestion ; utile en cas d'agitation et de troubles digestifs légers.", contraindications: "Allergie aux Astéracées (marguerite, arnica). Prudence pendant la grossesse.", usageNotes: "1 c. à café de fleurs séchées en infusion 10 min, 1 à 3 fois/jour." },
  { name: "Mélisse", category: "Plante", properties: "Calmante, favorise l'endormissement et apaise les troubles digestifs d'origine nerveuse.", contraindications: "Déconseillée pendant la grossesse (données insuffisantes). Prudence en cas d'hypothyroïdie.", usageNotes: "Infusion le soir ; souvent associée à la passiflore pour le sommeil." },
  { name: "Passiflore", category: "Plante", properties: "Anxiolytique doux, favorise le sommeil et réduit l'agitation et la nervosité.", contraindications: "Déconseillée en cas de dépression sévère ; éviter avec sédatifs sans avis. Grossesse : à éviter.", usageNotes: "Infusion ou extrait en fin de journée. Synergie avec valériane/mélisse." },
  { name: "Valériane", category: "Plante", properties: "Sédative, aide à l'endormissement et à la qualité du sommeil.", contraindications: "Peut majorer l'effet des somnifères/anxiolytiques. Éviter avant de conduire. Grossesse/allaitement : avis requis.", usageNotes: "Extrait sec le soir, en cure courte." },
  { name: "Ortie", category: "Plante", properties: "Reminéralisante (fer, silice), soutient l'élimination ; utile en cas de fatigue et terrain déminéralisé.", contraindications: "Prudence en cas d'œdèmes liés à une insuffisance cardiaque/rénale.", usageNotes: "Infusion de feuilles, en cure de 3 semaines." },
  { name: "Pissenlit", category: "Plante", properties: "Soutient les fonctions hépatique et rénale ; draineur classique des cures détox.", contraindications: "Calculs/obstruction des voies biliaires, ulcère. Allergie aux Astéracées.", usageNotes: "Racine/feuille en infusion ou décoction, cure de drainage au printemps/automne." },
  { name: "Romarin", category: "Plante", properties: "Tonique général et hépatique, soutient la digestion et la vitalité.", contraindications: "Hypertension non contrôlée, épilepsie, grossesse pour les formes concentrées.", usageNotes: "Infusion le matin/midi (éviter le soir : tonifiant)." },
  { name: "Gingembre", category: "Plante", properties: "Anti-nauséeux, stimule la digestion, tonique.", contraindications: "Prudence avec les anticoagulants et en cas de calculs biliaires.", usageNotes: "Frais râpé en infusion, ou en poudre dans l'alimentation." },
  { name: "Thym", category: "Plante", properties: "Soutien des voies respiratoires et antiseptique ; utile l'hiver.", contraindications: "Prudence en cas de troubles thyroïdiens ; grossesse pour formes concentrées.", usageNotes: "Infusion avec un peu de miel en cas de gorge irritée." },
  { name: "Aubépine", category: "Plante", properties: "Apaise la nervosité et soutient le système cardiovasculaire (palpitations d'origine émotionnelle).", contraindications: "Traitement cardiaque en cours : avis médical indispensable.", usageNotes: "Infusion ou extrait, en cure régulière." },
  { name: "Artichaut", category: "Plante", properties: "Soutient le foie et la digestion des graisses ; draineur hépatique.", contraindications: "Obstruction des voies biliaires, allergie aux Astéracées.", usageNotes: "Extrait de feuilles avant les repas, en cure." },
  { name: "Fenouil", category: "Plante", properties: "Digestif, anti-ballonnements et anti-spasmodique.", contraindications: "Allergies aux Apiacées ; prudence grossesse pour formes concentrées.", usageNotes: "Graines en infusion après les repas." },

  // ── Huiles essentielles ──
  { name: "Lavande vraie (HE)", category: "Huile essentielle", properties: "Calmante et relaxante, favorise le sommeil ; apaise petites irritations cutanées.", contraindications: "Éviter les 3 premiers mois de grossesse ; prudence chez le jeune enfant.", usageNotes: "1-2 gouttes en diffusion le soir, ou diluée dans une huile végétale en massage." },
  { name: "Tea tree (HE)", category: "Huile essentielle", properties: "Anti-infectieuse à large spectre (bactéries, mycoses) ; assainissante.", contraindications: "Grossesse/allaitement et jeunes enfants : avis requis. Toujours diluer.", usageNotes: "Usage local dilué ; jamais pur sur une grande surface." },
  { name: "Menthe poivrée (HE)", category: "Huile essentielle", properties: "Digestive, anti-nausée et utile contre les maux de tête (effet rafraîchissant).", contraindications: "Interdite femme enceinte/allaitante, enfant < 7 ans, épileptiques. Jamais près des yeux/voies respiratoires du jeune enfant.", usageNotes: "1 goutte sur un comprimé neutre après un repas lourd, ou diluée sur les tempes (adulte)." },
  { name: "Ravintsara (HE)", category: "Huile essentielle", properties: "Antivirale et tonifiante, soutien immunitaire pendant la saison froide.", contraindications: "Déconseillée 1er trimestre de grossesse et bébé < 3 mois ; prudence asthmatiques/épileptiques.", usageNotes: "2 gouttes diluées sur le thorax/poignets en prévention hivernale (adulte)." },
  { name: "Eucalyptus radié (HE)", category: "Huile essentielle", properties: "Décongestionnante des voies respiratoires hautes, expectorante douce.", contraindications: "Jeunes enfants et asthmatiques : prudence ; éviter en diffusion près des nourrissons.", usageNotes: "Diffusion courte ou dilué en friction thoracique (adulte)." },
  { name: "Citron (HE)", category: "Huile essentielle", properties: "Assainit l'air, soutient la digestion et le foie.", contraindications: "Photosensibilisante : pas d'exposition au soleil après application cutanée.", usageNotes: "Diffusion atmosphérique ; usage interne uniquement sur avis." },

  // ── Compléments / micronutrition ──
  { name: "Magnésium", category: "Complément", properties: "Soutient le système nerveux et musculaire ; utile en cas de stress, fatigue, crampes.", contraindications: "Insuffisance rénale sévère : avis médical. Excès = effet laxatif.", usageNotes: "Privilégier les formes bien tolérées (bisglycinate, glycérophosphate), souvent le soir." },
  { name: "Vitamine D3", category: "Complément", properties: "Immunité, santé osseuse et tonus ; carence fréquente en hiver.", contraindications: "Hypercalcémie, certaines pathologies : dosage sanguin conseillé.", usageNotes: "Supplémentation surtout d'octobre à mars ; idéalement guidée par un bilan." },
  { name: "Probiotiques", category: "Complément", properties: "Soutiennent l'équilibre du microbiote intestinal et le confort digestif.", contraindications: "Immunodépression sévère : avis médical.", usageNotes: "Cure de 1 à 3 mois, à distance des repas ou selon la souche." },
  { name: "Oméga-3 (EPA/DHA)", category: "Complément", properties: "Soutien cardiovasculaire, nerveux et anti-inflammatoire.", contraindications: "Prudence avec les anticoagulants ; choisir une source purifiée.", usageNotes: "Au cours d'un repas contenant des graisses." },
  { name: "Spiruline", category: "Complément", properties: "Riche en protéines et fer ; soutien en cas de fatigue et terrain déminéralisé.", contraindications: "Phénylcétonurie, hémochromatose, maladies auto-immunes : avis requis. Qualité/origine essentielles.", usageNotes: "Démarrer à faible dose et augmenter progressivement." },

  // ── Fleurs de Bach ──
  { name: "Rescue (fleurs de Bach)", category: "Fleur de Bach", properties: "Apaisement émotionnel en cas de coup de stress ou de choc émotionnel ponctuel.", contraindications: "Versions avec alcool : prudence (grossesse, enfants) — préférer sans alcool.", usageNotes: "Quelques gouttes en cas de besoin, sous la langue." },
  { name: "Mimulus (fleurs de Bach)", category: "Fleur de Bach", properties: "Pour les peurs identifiées du quotidien (parler en public, rendez-vous…).", contraindications: "Aucune connue ; accompagnement émotionnel, ne remplace pas un suivi.", usageNotes: "4 gouttes, 4 fois par jour, en cure." },

  // ── Plantes (enrichissement) ──
  { name: "Millepertuis", category: "Plante", properties: "Antidépresseur léger et anxiolytique doux, indiqué pour les états dépressifs légers à modérés, l'irritabilité et les troubles du sommeil liés au stress.", contraindications: "Nombreuses interactions graves (antidépresseurs, contraceptifs oraux, anticoagulants, antiviraux) ; contre-indiqué grossesse/allaitement et exposition solaire (photosensibilisant).", usageNotes: "Extrait sec standardisé, en cure de 4 à 6 semaines, avec avis médical et à distance de tout autre psychotrope." },
  { name: "Rhodiola", category: "Plante", properties: "Adaptogène tonifiant : améliore la résistance au stress, réduit la fatigue et soutient les fonctions cognitives.", contraindications: "Déconseillée en cas de trouble bipolaire, grossesse/allaitement ; stimulante (éviter le soir) ; interactions avec les antidépresseurs.", usageNotes: "200 à 400 mg d'extrait le matin à jeun, en cure de 6 à 12 semaines." },
  { name: "Ashwagandha", category: "Plante", properties: "Adaptogène qui réduit le cortisol, améliore la résistance au stress et favorise un sommeil de qualité.", contraindications: "Contre-indiquée grossesse, enfants < 12 ans et maladies auto-immunes ; interactions avec immunosuppresseurs et thyroïdiens.", usageNotes: "300 à 600 mg d'extrait le soir, en cure de 8 à 12 semaines." },
  { name: "Ginseng", category: "Plante", properties: "Tonique adaptogène contre la fatigue physique et mentale ; soutient l'immunité et les performances cognitives.", contraindications: "Contre-indiqué en cas d'hypertension, d'insomnie, sous anticoagulants/antidiabétiques ; déconseillé grossesse et cancers hormono-dépendants.", usageNotes: "200 à 400 mg d'extrait le matin, en cure de 4 à 6 semaines (max 3 mois)." },
  { name: "Éleuthérocoque", category: "Plante", properties: "Adaptogène doux (« ginseng sibérien ») : atténue la fatigue, soutient l'immunité et la tolérance au stress.", contraindications: "Déconseillé en cas d'hypertension sévère, de troubles cardiaques, grossesse/allaitement.", usageNotes: "400 à 800 mg d'extrait le matin, en cure de 4 à 8 semaines." },
  { name: "Chardon-Marie", category: "Plante", properties: "Hépatoprotecteur (silymarine) : soutient le foie en cas de surcharge et aide la digestion des graisses.", contraindications: "Contre-indiqué en cas d'obstruction biliaire et d'allergie aux Astéracées ; déconseillé pendant la grossesse.", usageNotes: "Extrait standardisé en silymarine avant les repas, en cure de 3 à 8 semaines." },
  { name: "Desmodium", category: "Plante", properties: "Hépatoprotecteur : protège et soutient la régénération des cellules du foie.", contraindications: "Par précaution, déconseillé grossesse/allaitement ; prudence avec les médicaments à métabolisme hépatique.", usageNotes: "Gélules ou teinture mère avant les repas, notamment après prise de médicaments ou d'excès, en cure de 3 à 6 semaines." },
  { name: "Harpagophytum", category: "Plante", properties: "Anti-inflammatoire et antalgique (« griffe du diable ») pour les douleurs articulaires, rhumatismes et lombalgies.", contraindications: "Contre-indiqué en cas d'ulcère, de calculs biliaires, grossesse/allaitement ; prudence avec anticoagulants et AINS.", usageNotes: "600 à 1200 mg d'extrait/jour en dehors des repas, en cure de 4 à 8 semaines." },
  { name: "Curcuma", category: "Plante", properties: "Anti-inflammatoire et antioxydant (curcumine) : douleurs articulaires, soutien digestif et hépatique.", contraindications: "Contre-indiqué en cas d'obstruction/calculs biliaires ; prudence à forte dose grossesse et sous anticoagulants.", usageNotes: "Extrait standardisé associé à la pipérine, au cours des repas, en cure de 4 à 8 semaines." },
  { name: "Échinacée", category: "Plante", properties: "Immunostimulant antiviral/antibactérien, en prévention et accompagnement des infections ORL hivernales.", contraindications: "Contre-indiquée en cas de maladies auto-immunes, sous immunosuppresseurs ou chimiothérapie ; déconseillée grossesse ; cures < 8 semaines.", usageNotes: "Dès les premiers signes d'infection, 7 à 10 jours, puis en prévention 3 semaines en hiver." },
  { name: "Sureau noir", category: "Plante", properties: "Antiviral et immunostimulant : soutient les défenses et réduit la durée des épisodes grippaux.", contraindications: "Baies crues toxiques (à cuire) ; déconseillé en cas de maladies auto-immunes et pendant la grossesse.", usageNotes: "Sirop, extrait ou infusion de fleurs dès les premiers symptômes, 2 à 3 fois/jour, 5 à 7 jours." },
  { name: "Ginkgo biloba", category: "Plante", properties: "Améliore la microcirculation cérébrale et soutient mémoire et concentration.", contraindications: "Contre-indiqué avec les anticoagulants ; à arrêter avant une chirurgie ; déconseillé grossesse/allaitement et < 18 ans.", usageNotes: "120 à 240 mg d'extrait standardisé/jour au cours des repas, en cure de 3 mois." },
  { name: "Vigne rouge", category: "Plante", properties: "Veinotonique et protecteur capillaire : insuffisance veineuse, jambes lourdes, varices.", contraindications: "Déconseillée grossesse/allaitement, < 18 ans et sous anticoagulants ; prudence antécédents de cancer du sein.", usageNotes: "360 à 720 mg d'extrait/jour, en cure de 4 à 12 semaines, surtout à la saison chaude." },
  { name: "Marron d'Inde", category: "Plante", properties: "Veinotonique anti-œdémateux (aescine) : tonifie les parois veineuses, soulage varices et hémorroïdes.", contraindications: "Contre-indiqué en cas d'insuffisance rénale/hépatique grave, grossesse, sous anticoagulants.", usageNotes: "Extrait standardisé en aescine au cours des repas, en cure de 6 à 8 semaines." },
  { name: "Reine-des-prés", category: "Plante", properties: "Anti-inflammatoire et antalgique (« aspirine végétale ») : douleurs articulaires, fièvre modérée, rétention d'eau.", contraindications: "Contre-indiquée en cas d'allergie aux salicylés, d'ulcère et avec les anticoagulants ; déconseillée grossesse.", usageNotes: "Infusion de sommités fleuries 3 fois/jour, en cure courte de 7 à 14 jours." },
  { name: "Sauge officinale", category: "Plante", properties: "Antihydrotique et phyto-œstrogène : bouffées de chaleur et sueurs de la ménopause ; aussi digestive.", contraindications: "Contre-indiquée en cas de cancer hormono-dépendant, grossesse/allaitement ; prudence avec un THS.", usageNotes: "Infusion de feuilles ou extrait sec, en cure de 8 à 12 semaines." },
  { name: "Gattilier", category: "Plante", properties: "Régulateur hormonal féminin : syndrome prémenstruel, cycles irréguliers, soutien de la périménopause.", contraindications: "Contre-indiqué en cas d'antécédents de cancer du sein, de protocole FIV ou de traitements hormonaux ; déconseillé grossesse.", usageNotes: "20 à 40 mg d'extrait le matin à jeun, en cure d'au moins 3 mois, idéalement suivie par un praticien." },
  { name: "Réglisse", category: "Plante", properties: "Adoucissante des muqueuses digestives et soutien surrénalien : gastrite, reflux, toux sèche, fatigue.", contraindications: "Contre-indiquée en cas d'hypertension, d'insuffisance cardiaque, grossesse, sous diurétiques/corticoïdes ; cures < 4 à 6 semaines.", usageNotes: "Décoction de racine ou extrait sec avant les repas, en cure courte (max 4 semaines)." },
  { name: "Bardane", category: "Plante", properties: "Dépuratif cutané : régule le sébum, soutient les peaux à problèmes (acné, eczéma) et la fonction hépato-rénale.", contraindications: "Déconseillée grossesse/allaitement et en cas d'allergie aux Astéracées ; prudence avec anticoagulants en usage prolongé.", usageNotes: "Décoction de racine ou gélules, en cure de 4 à 6 semaines, idéale au printemps/automne." },
  { name: "Achillée millefeuille", category: "Plante", properties: "Antispasmodique digestive et emménagogue : ballonnements, crampes menstruelles, règles irrégulières.", contraindications: "Contre-indiquée pendant la grossesse, en cas d'allergie aux Astéracées et avec traitements hormonaux/anticoagulants.", usageNotes: "Infusion de sommités fleuries 2 à 3 fois/jour, de préférence en 2e partie de cycle." },

  // ── Huiles essentielles (enrichissement) ──
  { name: "Niaouli (HE)", category: "Huile essentielle", properties: "Antivirale et expectorante : infections ORL et respiratoires, infections virales (herpès, zona).", contraindications: "Contre-indiquée grossesse/allaitement, pathologies hormono-dépendantes, enfants < 3 ans ; avis médical si asthme/épilepsie.", usageNotes: "Diluée à 20 % dans une huile végétale sur le thorax/dos ; diffusion par plages de 30 min." },
  { name: "Eucalyptus globuleux (HE)", category: "Huile essentielle", properties: "Expectorante et mucolytique puissante : bronchites profondes, toux grasse, états grippaux.", contraindications: "Réservée ados/adultes ; contre-indiquée grossesse/allaitement, enfants < 6 ans, asthmatiques et épileptiques sans avis.", usageNotes: "Diluée à 20 % sur le thorax/dos 4 fois/jour ; diffusion 30 min max." },
  { name: "Eucalyptus citronné (HE)", category: "Huile essentielle", properties: "Anti-inflammatoire et antalgique : arthrose, douleurs articulaires et musculaires, tendinites ; répulsif anti-moustiques.", contraindications: "Déconseillée 1er trimestre de grossesse et nourrissons < 3 mois ; irritante (toujours diluer) ; composés allergènes.", usageNotes: "Diluée à 20 % en massage local 2 à 3 fois/jour ; pas d'inhalation directe." },
  { name: "Gaulthérie couchée (HE)", category: "Huile essentielle", properties: "Anti-inflammatoire et antalgique de référence : douleurs musculaires, tendinites, courbatures, arthrite.", contraindications: "Contre-indiquée grossesse/allaitement, enfants < 6 ans, allergie à l'aspirine, troubles de la coagulation/anticoagulants ; usage cutané dilué uniquement.", usageNotes: "1 goutte dans 4 à 9 gouttes d'huile végétale en massage local 3 fois/jour ; jamais ingérée ni diffusée." },
  { name: "Hélichryse italienne (HE)", category: "Huile essentielle", properties: "Anti-hématome et cicatrisante exceptionnelle (« immortelle ») : ecchymoses, varices, cicatrices, circulation.", contraindications: "Déconseillée 1er trimestre de grossesse, troubles de la coagulation/anticoagulants ; avis pro si grossesse avancée.", usageNotes: "Pure ou diluée à 50 % en massage doux 2 à 3 fois/jour ; ne pas masser si fracture suspectée." },
  { name: "Géranium rosat (HE)", category: "Huile essentielle", properties: "Tonique, anti-infectieuse et antifongique cutanée : acné, eczéma, mycoses, vergetures.", contraindications: "Contre-indiquée nourrissons < 3 ans et 1er trimestre de grossesse ; fort potentiel allergène (test cutané, diluer à 20 %).", usageNotes: "Diluée à 20 % sur les zones à traiter ; en diffusion, mélangée à d'autres huiles, 30 min max." },
  { name: "Ylang-ylang (HE)", category: "Huile essentielle", properties: "Anxiolytique, calmante cardiaque et hypotensive : stress, palpitations, hypertension modérée.", contraindications: "Déconseillée 1er trimestre de grossesse et enfants < 3 ans en cutané ; prudence en cas d'hypotension ; nausées/céphalées si excès.", usageNotes: "Diffusion 30 min diluée ; diluée à 20 % sur le plexus solaire en cas de stress aigu." },
  { name: "Petit grain bigarade (HE)", category: "Huile essentielle", properties: "Anxiolytique et rééquilibrante nerveuse : stress, angoisses, insomnies, spasmes digestifs.", contraindications: "Déconseillée 1er trimestre de grossesse et nourrissons < 6 mois ; test cutané si terrain allergique (linalol).", usageNotes: "Diffusion ou inhalation sur mouchoir ; diluée à 20 % en massage du plexus ou du dos." },
  { name: "Orange douce (HE)", category: "Huile essentielle", properties: "Calmante, digestive et carminative : anxiété légère, sommeil, ballonnements ; assainit l'air.", contraindications: "Photosensibilisante (pas de soleil 6 h après application) ; prudence voie orale grossesse/enfants ; composés allergènes.", usageNotes: "Idéale en diffusion atmosphérique ; diluée à 20 % en massage abdominal." },
  { name: "Mandarine verte (HE)", category: "Huile essentielle", properties: "Sédative et digestive douce, bien tolérée : agitation, sommeil, troubles digestifs ; adaptée aux enfants.", contraindications: "Photosensibilisante (pas de soleil 12 h après application) ; déconseillée 1er trimestre de grossesse ; diluer (dermocaustique pure).", usageNotes: "Diffusion 20 min avant le coucher ; diluée à 10-20 % en massage abdominal." },
  { name: "Basilic tropical (HE)", category: "Huile essentielle", properties: "Antispasmodique digestive puissante : spasmes, crampes abdominales, nausées, digestions difficiles.", contraindications: "Contre-indiquée grossesse/allaitement, enfants < 6 ans, troubles hépatiques, anticoagulants ; usage oral bref (max 7 j).", usageNotes: "Diluée à 20 % en massage abdominal 3 fois/jour ; usage oral adulte sous guidance." },
  { name: "Laurier noble (HE)", category: "Huile essentielle", properties: "Anti-infectieuse, expectorante et antalgique : infections ORL, aphtes, douleurs dentaires, contractures.", contraindications: "Déconseillée 1er trimestre de grossesse et enfants < 6 ans ; très allergisante (test cutané 48 h impératif).", usageNotes: "Diluée à 50 % en application locale ; diffusion 30 min pour les voies respiratoires." },
  { name: "Origan compact (HE)", category: "Huile essentielle", properties: "Anti-infectieuse majeure (phénols) : infections bactériennes, virales, fongiques et parasitaires résistantes.", contraindications: "Contre-indiquée grossesse/allaitement et enfants < 12 ans ; dermocaustique et hépatotoxique à dose élevée ; cures courtes (max 2 semaines), adultes.", usageNotes: "Diluée à 10 % min en cutané ; usage oral adulte sous guidance, 5 à 10 jours max." },
  { name: "Romarin à cinéole (HE)", category: "Huile essentielle", properties: "Expectorante, antifongique et tonifiante mentale : ORL, fatigue intellectuelle, candidoses.", contraindications: "Réservée adultes/ados ; contre-indiquée grossesse (sauf diffusion après 3 mois), enfants < 6 ans, asthmatiques/épileptiques sans avis.", usageNotes: "Diluée à 20 % sur le thorax/dos 4 fois/jour ; diffusion 30 min pour la concentration." },
  { name: "Saro (HE)", category: "Huile essentielle", properties: "Antivirale, expectorante et neurotonique : alternative douce au ravintsara pour les infections ORL et l'immunité.", contraindications: "Déconseillée 1er trimestre de grossesse et nourrissons < 3 mois ; avis médical si asthme/épilepsie ; diluer (irritante).", usageNotes: "Diluée à 20 % sur le thorax/dos 4 à 5 fois/jour ; inhalation sèche sur mouchoir." },
  { name: "Palmarosa (HE)", category: "Huile essentielle", properties: "Antifongique et antibactérienne cicatrisante : mycoses cutanées et unguéales, acné, infections urinaires.", contraindications: "Contre-indiquée grossesse/allaitement et enfants < 6 ans ; très riche en géraniol (allergène, test cutané, diluer).", usageNotes: "Diluée à 20-50 % sur la zone à traiter 2 fois/jour." },
  { name: "Cyprès toujours vert (HE)", category: "Huile essentielle", properties: "Veinotonique et décongestionnante lymphatique : varices, jambes lourdes, hémorroïdes, toux sèche.", contraindications: "Contre-indiquée grossesse/allaitement, antécédents de cancers hormono-dépendants, fibromes ; enfants < 6 ans, asthmatiques/épileptiques.", usageNotes: "Diluée à 20 % en effleurage ascendant des jambes matin et soir." },
  { name: "Pin sylvestre (HE)", category: "Huile essentielle", properties: "Antiseptique respiratoire et stimulante surrénalienne (effet cortisone-like) : infections bronchiques, fatigue, rhumatismes.", contraindications: "Contre-indiquée grossesse/allaitement, enfants < 30 mois, épileptiques/asthmatiques ; cures < 3 semaines.", usageNotes: "Diluée à 20 % sur le thorax/dos ; diffusion 30 min pour assainir et soutenir l'immunité." },
  { name: "Camomille romaine (HE)", category: "Huile essentielle", properties: "Calmante et anxiolytique majeure : anxiété, stress, insomnie, spasmes nerveux, poussées dentaires du nourrisson.", contraindications: "Déconseillée 1er trimestre de grossesse et nourrissons < 3 mois ; avis si épilepsie ; allergie croisée Astéracées.", usageNotes: "Diluée à 20 % (adulte) sur le plexus/poignets ; à 5 % chez le nourrisson dès 3 mois." },
  { name: "Bois de hô (HE)", category: "Huile essentielle", properties: "Anti-infectieuse large spectre (linalol) et régénérante cutanée : ORL, mycoses, fatigue, peaux acnéiques ou matures.", contraindications: "Déconseillée 1er trimestre de grossesse et nourrissons < 3 mois ; forte teneur en linalol (test cutané).", usageNotes: "Pure sur petite zone ou diluée à 20 % en usage quotidien ; diffusion 30 min." },
  { name: "Marjolaine à coquilles (HE)", category: "Huile essentielle", properties: "Calmante et antispasmodique, équilibrante du système nerveux : stress, surmenage, insomnie, douleurs nerveuses.", contraindications: "Déconseillée 1er trimestre de grossesse et nourrissons < 3 mois ; prudence en cas d'hypotension sévère.", usageNotes: "Diffusion 20-30 min avant le coucher ; diluée à 20 % sur le plexus ou la voûte plantaire." },
  { name: "Clou de girofle (HE)", category: "Huile essentielle", properties: "Antalgique locale puissante (eugénol) et anti-infectieuse large spectre : douleurs dentaires, aphtes, mycoses.", contraindications: "Contre-indiquée grossesse/allaitement et enfants < 6 ans ; dermocaustique et hépatotoxique à dose élevée ; pas sous anticoagulants.", usageNotes: "Diluée à 10-20 % ; 1 goutte diluée sur la gencive au coton-tige pour une douleur dentaire." },
  { name: "Thym à linalol (HE)", category: "Huile essentielle", properties: "La plus douce des thyms : antibactérienne, antivirale, antifongique et immunostimulante (ORL, urinaire, mycoses).", contraindications: "Déconseillée 1er trimestre de grossesse et nourrissons < 3 mois ; contient du linalol (test cutané si terrain allergique).", usageNotes: "Dès 3 mois diluée à 5 % sur le thorax ; adulte 1 à 2 gouttes dans du miel ou diluée à 20 %." },

  // ── Compléments (enrichissement) ──
  { name: "Vitamine C", category: "Complément", properties: "Antioxydant qui soutient l'immunité, la synthèse du collagène et l'absorption du fer ; réduit la fatigue.", contraindications: "Doses > 2 g/j déconseillées en cas d'insuffisance rénale, d'hémochromatose ou de lithiase oxalique ; peut fausser la glycémie capillaire.", usageNotes: "200 à 500 mg/j avec un repas (ascorbate pour la tolérance), en cure de 1 à 3 mois." },
  { name: "Vitamine B12", category: "Complément", properties: "Essentielle au système nerveux et aux globules rouges ; indispensable aux végétaliens et après 50 ans.", contraindications: "Pas de toxicité connue, mais suivi conseillé si prise de metformine ou d'IPP et en supplémentation prolongée.", usageNotes: "Méthylcobalamine 1000 µg/j en sublingual le matin, en cure de 3 mois min en cas de carence." },
  { name: "Complexe Vitamines B", category: "Complément", properties: "Les 8 vitamines B : soutien du métabolisme énergétique, réduction de la fatigue, système nerveux.", contraindications: "B6 chronique > 50 mg/j : risque de neuropathie ; B6/B12 à forte dose déconseillées aux fumeurs ; prise tardive gênant le sommeil.", usageNotes: "Au petit-déjeuner pour la tolérance et éviter l'effet stimulant le soir, en cure de 2 à 3 mois." },
  { name: "Zinc", category: "Complément", properties: "Oligo-élément clé : immunité, cicatrisation, peau, équilibre hormonal ; antioxydant et anti-inflammatoire.", contraindications: "Ne pas dépasser 40 mg/j (carence en cuivre, troubles digestifs) ; espacer de 2 h des antibiotiques, du fer et des bisphosphonates.", usageNotes: "Bisglycinate ou citrate, 10 à 15 mg/j le matin à jeun, en cure de 1 à 3 mois." },
  { name: "Fer (bisglycinate)", category: "Complément", properties: "Fer chélaté très biodisponible et bien toléré pour corriger une carence ou une anémie ferriprive confirmée.", contraindications: "Contre-indiqué en cas d'hémochromatose et de MICI active ; interactions multiples ; jamais sans bilan sanguin préalable.", usageNotes: "14 à 28 mg/j le matin à jeun avec de la vitamine C ; éviter thé/café/laitages ; cure de 12 semaines avec contrôle." },
  { name: "Iode", category: "Complément", properties: "Indispensable à la synthèse des hormones thyroïdiennes et au développement cérébral fœtal.", contraindications: "Surdosage dangereux (hyper/hypothyroïdie) ; sans avis médical si pathologie thyroïdienne ou amiodarone ; enceinte max 250 µg/j.", usageNotes: "≈ 150 µg/j (adulte), souvent en complexe ou en algues (kelp), sous contrôle si antécédents thyroïdiens." },
  { name: "Sélénium", category: "Complément", properties: "Antioxydant qui soutient la thyroïde, l'immunité et la fertilité masculine.", contraindications: "Ne pas dépasser 400 µg/j (70 µg/j enceinte) ; éviter les doublons ; prudence chez l'homme à risque prostatique.", usageNotes: "55 à 100 µg/j en sélénométhionine le matin, en cure de 2 à 3 mois." },
  { name: "Curcumine (Curcuma)", category: "Complément", properties: "Polyphénol anti-inflammatoire et antioxydant : douleurs articulaires, confort digestif, soutien hépatique.", contraindications: "Contre-indiquée avec les anticoagulants et en cas de lithiase/obstruction biliaire ; déconseillée grossesse/allaitement.", usageNotes: "300 à 500 mg/j (avec pipérine ou forme liposomale) pendant un repas, en cure de 1 à 3 mois." },
  { name: "Coenzyme Q10 (CoQ10)", category: "Complément", properties: "Soutient la production d'énergie mitochondriale et la protection cardiovasculaire ; utile sous statines.", contraindications: "Interactions avec anti-vitamine K, statines, antihypertenseurs, hypoglycémiants : avis médical si traitement.", usageNotes: "Ubiquinol 100 à 200 mg/j pendant un repas gras, en cure de 3 mois min." },
  { name: "Berbérine", category: "Complément", properties: "Alcaloïde végétal qui régule la glycémie, améliore la sensibilité à l'insuline et réduit le LDL.", contraindications: "Risque d'hypoglycémie/hypotension avec antidiabétiques et antihypertenseurs ; contre-indiquée grossesse/allaitement ; supervision médicale requise.", usageNotes: "500 mg 2 à 3 fois/jour avant les repas, max 4 à 6 semaines avec surveillance glycémique." },
  { name: "Mélatonine", category: "Complément", properties: "Hormone du sommeil : réduit le temps d'endormissement et aide en cas de décalage horaire.", contraindications: "Déconseillée enceintes/enfants et en cas de maladies auto-immunes, épilepsie, asthme, troubles de l'humeur ; interactions médicamenteuses.", usageNotes: "Max 2 mg/prise (France), 30 à 60 min avant le coucher, en cure courte (1 à 4 semaines)." },
  { name: "Vitamine E (tocophérols)", category: "Complément", properties: "Antioxydant liposoluble protégeant les membranes ; soutien cardiovasculaire et cutané.", contraindications: "Déconseillée avec anticoagulants ; doses élevées risquées ; à arrêter avant une chirurgie ; hors apport alimentaire en grossesse.", usageNotes: "Vitamine E naturelle (d-alpha-tocophérol) 50 à 100 UI/j pendant un repas, cure de 2 à 3 mois." },
  { name: "Bêta-carotène (pro-vitamine A)", category: "Complément", properties: "Précurseur de la vitamine A : peau, vision, muqueuses ; action antioxydante.", contraindications: "Déconseillé aux fumeurs (risque accru de cancer du poumon) ; max 7 mg/j ; coloration orangée bénigne si excès.", usageNotes: "3 à 6 mg/j pendant un repas gras, en cure saisonnière, notamment avant l'exposition solaire." },
  { name: "Chlorella", category: "Complément", properties: "Microalgue riche en chlorophylle, protéines et fer ; soutien immunitaire et chélation des métaux lourds.", contraindications: "Contre-indiquée en cas d'hémochromatose, d'insuffisance rénale, sous anticoagulants (vitamine K) ou allergie aux algues.", usageNotes: "Chlorella bio à paroi brisée 3 à 5 g/j avant les repas, en cure de 3 semaines, en augmentant progressivement." },
  { name: "Gelée royale", category: "Complément", properties: "Tonifiante, immunostimulante et adaptogène : fatigue, changements de saison.", contraindications: "Contre-indiquée en cas d'allergie aux produits de la ruche, d'asthme allergique ou de terrain immunodéprimé ; réactions anaphylactiques rares.", usageNotes: "500 mg à 1 g/j de gelée fraîche le matin à jeun, en cure de 4 à 6 semaines, 2 à 3 fois/an." },
  { name: "Propolis", category: "Complément", properties: "Antibactérienne, antivirale et immunomodulante : prévention et soulagement des infections ORL.", contraindications: "Contre-indiquée en cas d'allergie aux produits de la ruche/pollen ; potentialise anticoagulants/AINS ; déconseillée grossesse/allaitement et jeunes enfants.", usageNotes: "500 à 1000 mg/j en gélules ou extrait le matin, en cure de 3 à 4 semaines." },
  { name: "Pollen d'abeille", category: "Complément", properties: "Superaliment protéiné, riche en vitamines B et antioxydants : fatigue, vitalité, immunité.", contraindications: "Contre-indiqué en cas d'allergie aux pollens/produits de la ruche (risque anaphylactique) ; débuter par une très faible dose.", usageNotes: "10 à 20 g/j le matin à jeun (pollen frais), en cure de 4 à 6 semaines." },
  { name: "Levure de bière", category: "Complément", properties: "Riche en vitamines B, protéines et sélénium : santé des cheveux, ongles et peau.", contraindications: "Contient du gluten (contre-indiquée si maladie cœliaque) ; prudence MICI et antibiotiques ; déconseillée grossesse/allaitement et < 12 ans sans avis.", usageNotes: "2 à 3 g/j mélangés aux aliments, en cure de 2 à 3 mois." },
  { name: "Ortie (feuilles)", category: "Complément", properties: "Reminéralisante et diurétique (calcium, fer, silice) : reminéralisation, arthrite légère, élimination urinaire.", contraindications: "Déconseillée en cas d'hémochromatose, d'insuffisance rénale sévère, d'hypertension non stabilisée et avec anticoagulants/diurétiques.", usageNotes: "300 à 900 mg/j d'extrait après les repas avec un grand verre d'eau, en cure de 3 à 6 semaines." },
  { name: "Collagène marin hydrolysé", category: "Complément", properties: "Protéine structurelle : élasticité et hydratation de la peau, confort articulaire, santé osseuse.", contraindications: "Contre-indiqué en cas d'allergie aux poissons/fruits de mer ; troubles digestifs transitoires possibles ; avis médical en grossesse.", usageNotes: "5 à 10 g/j (peau) à 10 à 15 g/j (articulations), avec de la vitamine C, en cure d'au moins 3 mois." },
  { name: "L-Glutamine", category: "Complément", properties: "Acide aminé carburant des entérocytes : soutien de la barrière intestinale, récupération, immunité.", contraindications: "Contre-indiquée en cas de cirrhose, d'insuffisance rénale sévère ou de maladies cardiaques avancées ; avis si grossesse/pathologie rénale.", usageNotes: "2 à 5 g/j à jeun dans de l'eau froide, en cure de 4 à 8 semaines." },
  { name: "Prébiotiques (inuline / FOS)", category: "Complément", properties: "Fibres qui nourrissent le microbiote (bifidobactéries, lactobacilles) : transit et équilibre de la flore.", contraindications: "À introduire progressivement (ballonnements) ; déconseillés à forte dose en cas de SII ou régime pauvre en FODMAP.", usageNotes: "5 à 10 g/j mélangés aux aliments, en augmentant sur 2 semaines, idéalement avec des probiotiques." },
  { name: "MSM (méthylsulfonylméthane)", category: "Complément", properties: "Soufre organique : synthèse du collagène/kératine, confort articulaire, soutien des phanères.", contraindications: "Contre-indiqué en cas de troubles rénaux sévères, grossesse/allaitement ; débuter à faible dose (tolérance digestive).", usageNotes: "1,5 à 3 g/j en 2 à 3 prises pendant les repas, en cure de 3 mois min." },

  // ── Fleurs de Bach (enrichissement) ──
  { name: "Olive (Olive)", category: "Fleur de Bach", properties: "Pour l'épuisement physique et mental profond après un effort prolongé ou une maladie ; restaure l'énergie vitale.", contraindications: "Accompagnement émotionnel, ne remplace pas un suivi médical ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Étoile de Bethléem (Star of Bethlehem)", category: "Fleur de Bach", properties: "Pour les chocs émotionnels, traumatismes et deuils ; favorise la récupération après un état de choc.", contraindications: "Ne remplace pas un suivi psychologique en cas de traumatisme sévère ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour ; possible en application locale diluée." },
  { name: "Noyer (Walnut)", category: "Fleur de Bach", properties: "Pour les périodes de transition (déménagement, deuil, ménopause) et la protection des influences extérieures.", contraindications: "Accompagnement émotionnel, ne remplace pas un suivi ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Marronnier blanc (White Chestnut)", category: "Fleur de Bach", properties: "Pour les pensées intrusives et ruminations qui empêchent concentration et sommeil ; ramène la paix de l'esprit.", contraindications: "Ne remplace pas une prise en charge des troubles anxieux/du sommeil ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, y compris avant le coucher." },
  { name: "Chèvrefeuille (Honeysuckle)", category: "Fleur de Bach", properties: "Pour la nostalgie et l'attachement au passé ; aide à se réancrer dans le présent.", contraindications: "Ne remplace pas un suivi psychologique en cas de deuil/dépression ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans de l'eau." },
  { name: "Impatience (Impatiens)", category: "Fleur de Bach", properties: "Pour l'impatience, l'irritabilité et la tension nerveuse ; développe patience et tolérance.", contraindications: "Accompagnement émotionnel, ne remplace pas un suivi médical ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Mélèze (Larch)", category: "Fleur de Bach", properties: "Pour le manque de confiance en soi et la peur d'échouer ; restaure l'assurance.", contraindications: "Ne remplace pas un accompagnement de l'estime de soi ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Tremble (Aspen)", category: "Fleur de Bach", properties: "Pour les peurs vagues et inexplicables et les angoisses sans cause identifiée ; ramène la sérénité.", contraindications: "Ne remplace pas un suivi en cas de troubles anxieux sévères ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans de l'eau." },
  { name: "Pin sylvestre (Pine)", category: "Fleur de Bach", properties: "Pour la culpabilité excessive et l'auto-critique permanente ; développe l'auto-compassion.", contraindications: "Ne remplace pas un suivi en cas de culpabilité pathologique ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Charme (Hornbeam)", category: "Fleur de Bach", properties: "Pour la fatigue mentale et la procrastination (sentiment d'épuisement avant l'effort) ; ravive l'élan.", contraindications: "Ne remplace pas un bilan en cas de fatigue chronique ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, de préférence le matin." },
  { name: "Gentiane (Gentian)", category: "Fleur de Bach", properties: "Pour le découragement au moindre obstacle ; aide à persévérer et à retrouver confiance.", contraindications: "Ne remplace pas un suivi en cas de dépression ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans de l'eau." },
  { name: "Genêt (Gorse)", category: "Fleur de Bach", properties: "Pour le désespoir et la résignation ; ramène l'espoir et la volonté d'avancer.", contraindications: "Ne remplace pas un suivi en cas de dépression profonde ou d'idées suicidaires ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Houx (Holly)", category: "Fleur de Bach", properties: "Pour la jalousie, l'envie et la colère ; ouvre le cœur à la bienveillance.", contraindications: "Ne remplace pas un suivi en cas de troubles relationnels graves ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Chicorée (Chicory)", category: "Fleur de Bach", properties: "Pour la possessivité et le besoin d'attention ; aide à aimer librement et sans attente.", contraindications: "Ne remplace pas un accompagnement des troubles relationnels ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans de l'eau." },
  { name: "Clématite (Clematis)", category: "Fleur de Bach", properties: "Pour les rêveurs peu ancrés et le manque de concentration ; aide à se recentrer sur le réel.", contraindications: "Ne remplace pas une évaluation des troubles attentionnels ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Pommier sauvage (Crab Apple)", category: "Fleur de Bach", properties: "Pour la honte et le sentiment d'impureté ; aide à accepter ses imperfections.", contraindications: "Ne remplace pas un suivi dermatologique/psychiatrique ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour ; possible en application locale diluée." },
  { name: "Hêtre (Beech)", category: "Fleur de Bach", properties: "Pour l'intolérance et la critique facile ; développe empathie et ouverture.", contraindications: "Ne remplace pas un suivi des troubles relationnels ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans de l'eau." },
  { name: "Chêne (Oak)", category: "Fleur de Bach", properties: "Pour ceux qui luttent au-delà de leurs limites sans s'arrêter ; aide à reconnaître ses limites et à se reposer.", contraindications: "Ne remplace pas un bilan en cas de burn-out ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Saule (Willow)", category: "Fleur de Bach", properties: "Pour l'amertume et le ressentiment ; ramène la responsabilité personnelle et l'optimisme.", contraindications: "Ne remplace pas un suivi en cas de dépression ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans de l'eau." },
  { name: "Vigne (Vine)", category: "Fleur de Bach", properties: "Pour les personnalités autoritaires et inflexibles ; développe respect et leadership bienveillant.", contraindications: "Ne remplace pas un accompagnement des troubles de la personnalité ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
  { name: "Verveine (Vervain)", category: "Fleur de Bach", properties: "Pour l'enthousiasme excessif et le surmenage par idéalisme ; ramène équilibre et modération.", contraindications: "Ne remplace pas un suivi en cas de surmenage/anxiété ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans de l'eau." },
  { name: "Moutarde (Mustard)", category: "Fleur de Bach", properties: "Pour la mélancolie profonde et soudaine sans cause apparente ; ramène la joie intérieure.", contraindications: "Ne remplace pas un suivi en cas de dépression diagnostiquée ; versions alcoolisées : prudence grossesse/enfants.", usageNotes: "4 gouttes, 4 fois/jour, sous la langue ou dans un verre d'eau." },
];

/**
 * Insère les fiches globales MANQUANTES (idempotent par nom). S'exécute à chaque
 * démarrage : crée les nouvelles entrées du catalogue sans dupliquer l'existant.
 */
export async function seedNaturalSolutions(): Promise<void> {
  try {
    const existing = await storage.listNaturalSolutions(-1); // -1 = user inexistant → uniquement les globales
    const seen = new Set(existing.filter((s) => s.userId === null).map((s) => s.name.trim().toLowerCase()));
    let added = 0;
    for (const s of DEFAULT_SOLUTIONS) {
      if (seen.has(s.name.trim().toLowerCase())) continue;
      await storage.createNaturalSolution({ userId: null, ...s } as any);
      added++;
    }
    if (added > 0) console.log(`[seed] base de solutions : ${added} nouvelle(s) fiche(s) globale(s) ajoutée(s)`);
  } catch (e: any) {
    console.warn("[seed] seedNaturalSolutions échoué (best-effort):", e?.message || e);
  }
}
